openapi: 3.1.0
info:
  title: ForumAPI
  version: 1.0.0
  description: RESTful API for forum application (final submission Dicoding Javascript Backend Expert)
servers:
  - url: http://localhost:5000
    description: Local
  - url: https://www.easy-taxis-build-brightly.a276.dcdg.xyz/
    description: Submission server
paths:
  /users:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [username, password, fullname]
              properties:
                username:
                  type: string
                password:
                  type: string
                fullname:
                  type: string
      responses:
        '201':
          description: User created
        '400':
          description: Invalid input
  /authentications:
    post:
      summary: Login user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [username, password]
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Login success
        '401':
          description: Unauthorized
  /threads:
    post:
      summary: Create a new thread
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [title, body]
              properties:
                title:
                  type: string
                body:
                  type: string
      responses:
        '201':
          description: Thread created
        '400':
          description: Invalid input
        '401':
          description: Unauthorized
    get:
      summary: Get all threads
      responses:
        '200':
          description: List of threads
  /threads/{threadId}:
    get:
      summary: Get thread detail
      parameters:
        - name: threadId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Thread detail
        '404':
          description: Thread not found
    put:
      summary: Update a thread
      security:
        - bearerAuth: []
      parameters:
        - name: threadId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - title
                - body
              properties:
                title:
                  type: string
                body:
                  type: string
      responses:
        '200':
          description: Thread updated
        '400':
          description: Invalid input
        '401':
          description: Unauthorized
        '404':
          description: Thread not found
    delete:
      summary: Delete a thread
      security:
        - bearerAuth: []
      parameters:
        - name: threadId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Thread deleted
        '401':
          description: Unauthorized
        '404':
          description: Thread not found
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
